Implemented functionality for Category, refactored Book logic
kacper-kukula/book-store pull request #10
Opened 2024-04-07 00:03 UTC by kacper-kukula

2024-04-08 10:57 UTC, d1sam requested changes
Good job, but there are some changes, that should be according my comments.

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/dto/book/BookRequestDto.java
> +        @NotNull Set<@NotBlank String> categories
```suggestion
        @NotNull Set<Long> categoryIds
```

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN') or hasRole('ROLE_USER')")
when we use `hasRole`, we don't write prefix **ROLE_**. you can use `hasAnyRole` instead `or`

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/mapper/BookMapper.java
> +    default void setCategoryIds(@MappingTarget BookResponseDto bookResponseDto, Book book) {
what about body of this method?

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/mapper/BookMapper.java
> +                           Set<Category> categoriesSet);
please remove it, because `categories` in `BookRequestDto` are ids.

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/mapper/BookMapper.java
> +    Book toModel(BookRequestDto bookRequestDto, Set<Category> categoriesSet);
```suggestion
      @Mapping(target = "categories", ignore = true)
  Book toEntity(BookRequestDto bookDto);
```

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/mapper/BookMapper.java
> +    default Set<String> mapCategoryToString(Set<Category> categories) {
write with `ids`

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/model/Book.java
> +    @ManyToMany(cascade = CascadeType.REMOVE, fetch = FetchType.EAGER)
please avoid `EAGER` fetch type. please read [here](https://stackoverflow.com/a/24154042) why you shouldn't use `EAGER`

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/model/Book.java
> +    )
```suggestion
    )
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
```

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/model/User.java
>      @JoinTable(
please remove EAGER fetch type

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/repository/book/BookRepository.java
>  public interface BookRepository extends JpaRepository<Book, Long>, JpaSpecificationExecutor<Book> {
```suggestion
@Repository
public interface BookRepository extends JpaRepository<Book, Long>, JpaSpecificationExecutor<Book> {
```

2024-04-08 10:57 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-create-categories-table.yaml
> +                  type: BIT
```suggestion
                  type: BOOLEAN
```

2024-04-08 10:57 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-create-categories-table.yaml
> +                  defaultValue: 'false'
```suggestion
                  defaultValue: false
```

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/repository/book/BookSpecificationBuilder.java
> +            spec = spec.and(specificationProviderManager.getSpecificationProvider("categories")
please avoid String literals and magic numbers.

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/repository/book/spec/CategoriesSpecificationProvider.java
> +public class CategoriesSpecificationProvider implements SpecificationProvider<Book> {
please avoid String literals

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/repository/book/spec/CategoriesSpecificationProvider.java
> +                root.get("categories").in(Arrays.stream(params).toArray());
```suggestion
                root.get("categories").in(params);
```

2024-04-08 10:57 UTC, d1sam commented on src/main/java/com/bookstore/repository/category/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
```suggestion
@Repository
public interface CategoryRepository extends JpaRepository<Category, Long> {
```

2024-04-08 21:07 UTC, kacper-kukula commented on src/main/java/com/bookstore/repository/book/spec/CategoriesSpecificationProvider.java
> +                root.get("categories").in(Arrays.stream(params).toArray());
it gives a "yellow" error in IntelliJ: Confusing argument 'params', unclear if a varargs or non-varargs call is desired.

It was said on the lecture to use Arrays.stream(params).toArray()

2024-04-15 10:22 UTC, nowickimj approved these changes
Small remark but generally looks good.

2024-04-15 10:22 UTC, nowickimj commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +                .collect(Collectors.toSet());
Duplicated code

2024-04-15 10:33 UTC, merged