Added Order and OrderItem feature
kacper-kukula/book-store pull request #12
Opened 2024-04-19 22:48 UTC by kacper-kukula

2024-04-22 09:07 UTC, nowickimj requested changes

2024-04-22 09:07 UTC, nowickimj commented on src/main/java/com/bookstore/dto/order/OrderRequestDto.java
> +public record OrderRequestDto(
If this request class is not generic and is associated with specific operation, please make names more self-explainatory as the current name doesn't say much about its purpose. For example "CreateOrderRequestDto" or "UpdateOrderRequestDto".

2024-04-22 09:07 UTC, nowickimj commented on src/main/java/com/bookstore/dto/order/OrderItemResponseDto.java
> +public record OrderItemResponseDto(
A hint, not mandatory: As your API is resource-oriented (in this case we're talking about order-oriented services), you can remove "Response" from names of the DTO entities. You are returning a resource entity itself, not any specific response.

2024-04-22 09:07 UTC, nowickimj commented on src/main/java/com/bookstore/dto/order/OrderStatusRequestDto.java
> +public record OrderStatusRequestDto(
`UpdateOrderStatusRequestDto` ?

2024-04-22 09:07 UTC, nowickimj commented on src/main/java/com/bookstore/model/OrderItem.java
> +@Table(name = "order_items")
Shouldn't you consider `@SQLDelete` & `@Where` here as well?

2024-04-22 09:07 UTC, nowickimj commented on src/main/java/com/bookstore/service/impl/OrderServiceImpl.java
> +        Order order = orderRepository.findById(orderId)
You might consider using `getReferenceById` which returns the entity instead of the optional. 
1. It fetches data lazily which will be perfect for transactions.
2. It EXPECTS object to exist and will throw exception otherwise so no need for `orElseThrow()` handling.

More info here: https://www.baeldung.com/spring-data-jpa-getreferencebyid-findbyid-methods

2024-04-22 09:07 UTC, nowickimj commented on src/main/java/com/bookstore/service/impl/OrderServiceImpl.java
> +
1. No need for variable here. `findAllByUser(getCurrentUser())`
2. Redundant new line.

2024-04-22 16:56 UTC, kacper-kukula commented on src/main/java/com/bookstore/model/OrderItem.java
> +@Table(name = "order_items")
I considered it, yes, but I have `cascade = CascadeType.ALL` on the `Set<OrderItem>` in `Order`, so the Cascades will delete it permamently anyway?

2024-04-23 12:40 UTC, d1sam requested changes
Good job, but there are some changes, that should be done!

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/dto/order/UpdateOrderStatusRequestDto.java
> +        String status
```suggestion
        @NotNull(message = "can't be empty.") Order.Status status
```

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/model/OrderItem.java
> +@Table(name = "order_items")
It's better to add also `@SQLDelete` & `@Where`

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/model/Order.java
> +    private LocalDateTime orderDate;
```suggestion
    @CreationTimestamp
    @Column(nullable = false)
    private LocalDateTime orderDate;
```

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/service/OrderService.java
> +    List<OrderResponseDto> findOrderHistory();
```suggestion
    List<OrderResponseDto> findOrderHistory(Long userId, Pageable pageable);
```

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/service/OrderService.java
> +    List<OrderItemDto> findAllFromOrder(Long orderId);
```suggestion
    List<OrderItemDto> findAllFromOrder(Long orderId, Pageable pageable);
```

2024-04-23 12:40 UTC, d1sam commented on src/main/resources/db/changelog/changes/10-create-orders-table.yaml
> +                    nullable: false
```suggestion
                  constraints:
                    nullable: false
                    references: users(id)
                    foreignKeyName: fk_orders_user_id
                    deleteCascade: true
```

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/service/impl/OrderServiceImpl.java
> +    }
It's better to getCurrentUser() on Controller layer and then pass userId to Service layer.

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/service/impl/OrderServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional(readOnly = true)
```

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/service/impl/OrderServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional(readOnly = true)
```

2024-04-23 12:40 UTC, d1sam commented on src/main/java/com/bookstore/service/impl/OrderServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional(readOnly = true)
```

2024-04-24 07:39 UTC, nowickimj requested changes
One minor fix

2024-04-24 07:39 UTC, nowickimj commented on src/main/java/com/bookstore/model/Order.java
> +@SQLRestriction("is_deleted = FALSE")
Good call, I recently saw that `@Where` got deprecated.

2024-04-24 07:39 UTC, nowickimj commented on src/main/java/com/bookstore/service/impl/OrderServiceImpl.java
> +        Order order = orderRepository.getReferenceById(orderId);
You used `getReferenceById()` here but forgot to replace other occurrences below - please fix that.
Btw. too much much new lines here IMO.

2024-04-25 14:01 UTC, nowickimj approved these changes

2024-04-25 15:10 UTC, merged