Implemented controller, Mapper, DTOs
kacper-kukula/book-store pull request #2
Opened 2024-03-15 23:57 UTC by kacper-kukula

2024-03-17 14:57 UTC, okuzan requested changes

2024-03-17 14:57 UTC, okuzan commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +        }
make repo return optional to handle this gracefully

2024-03-17 14:57 UTC, okuzan commented on src/main/java/com/bookstore/controller/impl/BookControllerImpl.java
> +@RequestMapping(value = "/api/books")
consider extracting this common URL prefix to properties: `server.servlet.context-path=/api`

2024-03-17 14:57 UTC, okuzan commented on src/main/java/com/bookstore/repository/impl/BookRepositoryImpl.java
> +            return entityManager.find(Book.class, id);
```suggestion
            return Optional.ofNullable(entityManager.find(Book.class, id));
```

2024-03-19 10:14 UTC, nowickimj requested changes

2024-03-19 10:14 UTC, nowickimj commented on src/main/java/com/bookstore/controller/BookController.java
You may remove this interface.

2024-03-19 10:14 UTC, nowickimj commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(book);
Please refactor this method to not store the `book` variable and return results immediately - use `Optional.map()` method.

2024-03-19 10:14 UTC, nowickimj commented on src/main/java/com/bookstore/controller/BookController.java
> +
I see that sometimes you put a new line here and sometimes you don't - please make sure that you keep your code consistent.

2024-03-20 08:58 UTC, nowickimj approved these changes
As of my experience, I see new lines after the class declaration very rarely, but you can have it your way as long as you keep it consistent :)

2024-03-20 17:49 UTC, merged